ansys/pysystem-coupling

.coveragerc
.github/workflows/ci.yml
README.rst
codecov.yml

Uncomment coverage upload action now that we are public
Exclude the generated API code as it comprises mechanical wrapping of data model and commands. Coverage report is misleading and unrealistic for these files.

Enable coverage upload

---

src/ansys/systemcoupling/core/__init__.py

Minor change when running on Windows: from `USER_DATA_PATH` resolving to `%LocalAppData%\ansys_systemcoupling_core\ansys_systemcoupling_core`, changed to `%LocalAppData%\Ansys\ansys_systemcoupling_core` using the same root folder `%LocalAppData%\Ansys` as other applications. No change on Linux, resolves to `~/.local/share/ansys_systemcoupling_core`.
Original issue tracker https://github.com/ansys/pyfluent/issues/1588
Same Windows data path naming scheme as in https://github.com/ansys/pyfluent/pull/1615, https://github.com/ansys/pymapdl/pull/2064, https://github.com/ansys/pyprimemesh/pull/485, https://github.com/ansys/ansys-tools-path/pull/44
Also removed try-except block
Food for thought: data path and examples folders are immediately created when `import ansys.systemcoupling.core`, might …

Standardizing Windows data path

---

.github/workflows/ci.yml

As title says - you should be using the ``GITHUB_TOKEN`` secret

fix: deployment of dev docs

---

doc/.vale.ini

We are seeing vale errors appearing in current PRs. They appear to be spurious complaints about substrings such as `"n.S"` missing a space. Presumably these are being interpreted as end of sentences, with a full stop, whereas in fact these substrings come from Python paths to modules, classes, etc.
See MAPDL #2394 where the fix is applied there to solve similar errors.

Ignore some tokens that are giving spurious errors in vale

---

.github/workflows/ci.yml
tests/test_mocksolve_container.py

The issue is that the `doc-deploy-dev` action is failing, saying it can't find the "documentation-html" artifact. This artifact does appear to be present in the build. Prior to this, the documentation upload action `upload-artifact` was upgraded via a dependabot PR. Therefore trying a revert here, downgrading `upload-artifact` back to 3 from 4.
Note that the documentation deployment action only happens on a merge to `main` so this was not detected immediately. Furthermore the upstream _doc build_ task failed when the `upload-artifact` PR was initially merged to `main`, which further hid the issue.

Try to fix recent build failure - possibly arising from action upgrade

---

tests/test_mocksolve_container.py

A more up to date SyC image build has caused the "mock solver" unit test to fail. This is more like a regression test run via the unit test system so such failures would be expected from time to time.
Updated the test in a manner that is compatible with older versions.

Fix unit test failure resulting from new container

---

.pre-commit-config.yaml
doc/datamodel_rstgen.py
doc/source/conf.py
doc/source/getting_started/index.rst
doc/source/users_guide/analysis_setup.rst
doc/source/users_guide/index.rst
doc/source/users_guide/syc_datamodel.rst
doc/source/users_guide/syc_persistence.rst
doc/source/users_guide/syc_solution.rst
examples/00-systemcoupling/oscillating_plate.py
examples/00-systemcoupling/parametric_sweep_vel.py
src/ansys/systemcoupling/core/util/pathstr.py

This is motivated by wanting to add the `add-license-header` hook from `ansys/pre-commit-hooks` to our pre-commit config. We can use `add-license-header` to update all of our code with the required license headers and maintain license headers in future. This hook will be added in a _follow-up_ PR. The aim here is create a good base for that addition.
* Bring some of the pre-commit tools up to date. 
* Relax the restrictions on directories the tools are applied to. 
* Run pre-commit over all files and merge updates.
Regarding the excluded directories, prior to this change we exclude `examples/` and `doc/`. It's not clear why these were excluded. Certainly, we don't want to exclude `examples/` when we add the license header hook. Also, we are at present effectively missing the use of the …

Update pre-commit config

---

.github/workflows/ci.yml
src/ansys/systemcoupling/core/adaptor/impl/get_syc_version.py
tests/test_mocksolve_container.py

The 24.1 API has up to now been built using the "latest" SyC image which was actually quite out of date. Switch now to the newly built `v24.1.0` image in preparation for next PySyC release. This is based on the 24.1 release build of SyC. 
Also adjust the list of Python versions we test against in line with other products. Drop 3.8 and add 3.11.
Also, fix an issue found during this work, whereby the `23_1` version of the API was not being built because of a logic error in the "get version" code.

Build 241 API using release image

---

README.rst
doc/source/conf.py
doc/source/contributing.rst
doc/source/getting_started/index.rst
doc/source/users_guide/analysis_setup.rst
doc/source/users_guide/index.rst
doc/source/users_guide/syc_solution.rst
src/ansys/systemcoupling/core/__init__.py

* Modify any references to current/default version to refer to 24.1.
* General sweep through doc to pick up any issues, tweak wording here and there, etc.
* Fix navigation bar - version selector had been removed at some point.

Prepare doc for next release

---

.github/workflows/ci.yml

Prepare for new release (0.4) targeting Ansys 2024 R1.
* Only build API and test using versioned images up to v24.1.0

Final preparation for new release

---

.github/workflows/ci.yml
pyproject.toml

New version bump following 0.4.0 release.
Start building 24.2 API and run unit tests for 24.2 using "latest" image.

Bump version to 0.5.dev0

---

doc/source/getting_started/index.rst
pyproject.toml

Bring PySystemCoupling into line with other products, where the current  range of supported Python versions is `>=3.9, <3.13`.
This should have been updated for the recent release. The changes here will be cherry-picked into a new point release.

Fix supported Python version range

---

pyproject.toml
src/ansys/systemcoupling/core/__init__.py
src/ansys/systemcoupling/core/client/grpc_client.py
src/ansys/systemcoupling/core/session.py
src/ansys/systemcoupling/core/util/file_transfer.py
tests/test_pim.py

Modify `launch()` such that if we are running in an environment where `PyPIM` is configured, PIM will be used to launch an instance and it will be connected to.
Also expose a direct `launch_remote()` function that assumes that `PyPIM` is known to be configured.
In addition `upload_file` and `download_file` methods are added to the `Session` interface. These reduce to doing nothing unless `pyPIM` is configured. In a PIM environment they are needed to be able to exchange files with the remote instance as there is no mapping of the container file system to the local one.

Support 'PIM' launch in configured environment

---

src/ansys/systemcoupling/core/util/logging.py

Context: We use pysystem-coupling for the Volitare solution. Volitare is a SAF-based solution. GLOW provides logging infrastructure for us to use the native Python logging module to write to SAF log files. We found an issue where specific logging levels (debug, info) were not writing to the SAF log files.
After a deep investigation, I found the culprit to be this block of code. Specifically, [line 66](https://github.com/ansys/pysystem-coupling/blob/b71a597027b02302084ea9c6a026c850486a6320/src/ansys/systemcoupling/core/util/logging.py#L66), combined with the fact that the default value for `level` on line 57 is `ERROR`, means that the log level for the global Python logger is set in any Python script where SyC is imported. You can see what that looks like for Volitare …

fix: use a named logger instead of the global logger

---

src/ansys/systemcoupling/core/adaptor/impl/injected_commands.py
src/ansys/systemcoupling/core/participant/manager.py
src/ansys/systemcoupling/core/session.py

It has been found in some current WIP that passing the "category root" API object into `get_injected_cmd_map` is not always sufficient and that having access to the `Session` can make sense. As this is a change that potentially is more widely useful, it is being factored out now from the WIP branch. This will also simplify the WIP branch and help to avoid the possibility of conflicts.

Pass whole Session object into get_injected_cmd_map

---

.github/workflows/ci.yml

Current code base targets 24.1 by default and has been using the "latest" container, generated during 24.2 development, for unit testing and API generation of 24.2. Switching now to use a recently built v24.2.0 container, This frees us up to start using "latest" for 25.1 and is also the first step on the way to preparing for a new release of PySystemCoupling, targeting 24.2.

Switch from "latest" to recent "v24.2.0" container for workflows

---

src/ansys/systemcoupling/core/adaptor/impl/syc_proxy.py
src/ansys/systemcoupling/core/adaptor/impl/syc_proxy_interface.py
src/ansys/systemcoupling/core/adaptor/impl/types.py
tests/test_datamodel.py

Prior to this change, if a property did not exist in the current state, a query for it via "property path" syntax:
`value = syc.setup.solution_control.time_step_size`
would return an empty dictionary.
This is inconsistent with how System Coupling behaves and also with how existing but unset properties are represented in the state. In the case here, the property `time_step_size` could be missing entirely from the state either because `solution_control` is uninitialised or because other set-up renders `time_step_size` unavailable. (Either way, `time_step_size` is recognised as a _potentially_ available variable - an exception would be thrown if an arbitrary property name were queried.)
The cause of the issue was the implementation delegating to the System Coupling `GetState` query which, …

Query of missing property now returns None

---

pyproject.toml

`ansys-api-systemcoupling`, the gRPC API package on which PySystemCoupling depends, has had a version update that relaxes its `protobuf` version requirements and in particular supports `protobuf 4.x`. This is now needed because the 25.1 SystemCoupling server has had the protobuf updated in the common Python package.
There was also an explicit dependency on `protobuf` mentioned in the `pyptroject.toml` here, which I don't think was needed.

Dependency on ansys-api-systemcoupling modified to latest version

---

.github/workflows/ci.yml
src/ansys/systemcoupling/core/client/syc_container.py
src/ansys/systemcoupling/core/session.py
tests/test_mocksolve_container.py

Start building against a new "latest" (251) container.
Changes were needed to handle the new SyC licensing checks.

API build and unit testing with 'latest' image

---

.github/workflows/ci.yml
doc/source/getting_started/index.rst
pyproject.toml

PyAnsys is dropping support for Python 3.9 on the next metapackage release and PyAnsys products are encouraged to follow suit.
We need to move to 3.10 as the doc build version in any case to allow Sphinx to be upgraded to v4.

Drop Python 3.9 support

---

doc/source/conf.py
pyproject.toml

Update Ansys Sphinx Theme dependency. Use latest point release from recent v1 release.
Also, follow the recommendation we have been given to switch from using `html_logo` option in the `conf.py` to using `logo` in the `html_theme_options` dictionary.

Update Ansys Sphinx Theme to use new v1 release

---

.github/workflows/ci.yml

During recent work on Sphinx doc generation, the `test` job in the `ci.yml` workflow definition was disabled. This was then inadvertently merged to `main`.

Re-enable 'test' job in workflow 

---

.pre-commit-config.yaml
LICENSE

Pre-commit started failing locally for me on the `update-license-headers` hook. It turned out that the version being used was quite  out of date, and that updating to the latest version resolved the issue. 
Note that the LICENSE file itself that is updated in this PR was updated by runnin ght enew hook locally.

MAINT: Update update-license-header version

---

doc/source/contributing.rst

Since starting to build Sphinx Gallery examples in GitHub builds, some remarks in the `contributing.rst` file have been misleading. They are now removed.
This addresses #350.

Fix Contributing section re Sphinx Gallery generation

---

.github/workflows/ci.yml

After a recent merge to main of a dependabot PR, the build on `main` failed, even though the PR build itself was fine. This seems to be because of new requirements of the `ansys/actions/doc-deploy-dev@v8` action for `bot-user` and `bot-email` arguments and nothing to do with the changes that were merged. The new required inputs are added in this PR.

MAINT: add new arguments needed by doc-deploy-dev action

---

.github/actions/generate-api/action.yml
.github/actions/unit-test/action.yml
.github/workflows/ci.yml
doc/source/conf.py

Using v3 of upload-artifact now causes an error in the workflow.
There is one remaining use. Upgrade it to v4.

MAINT: remove last use of v3 or upload-artifact action

---

pyproject.toml

Builds on main seemed to started failing when this bump was merged. 
It is not clear why but revert for now and check that builds pass again.

FIX: revert bump of ansys-fluent-core

---

pyproject.toml

Reverts ansys/pysystem-coupling#468
For some reason not fully understood, this update fails the doc build when merged to main, though it passes on the branch.

Revert "Bump ansys-fluent-core from 0.29.0 to 0.30.2"

---

.github/workflows/ci.yml
.gitignore
README.rst
pyproject.toml

Bump supported Python versions to 3.13.
Trying to make 3.13 the "main" version for doc builds etc. fails because of issues with satisfying all dependencies. It is still worth proceeding with the support for 3.13 but, for now, the "main" version has been bumped to 3.12.
Addresses #433.

MAINT: support Python 3.13

---

AUTHORS
CONTRIBUTORS.md
patches/README.txt

This addresses issues #409 and #410.

MAINT: add AUTHORS and CONTRIBUTORS files

---

.github/workflows/ci.yml
pyproject.toml

As well as the version bump, also includes a cherry-picked commit from `release/0.9` branch in which the release doc job needed fixing.

MAINT: Post-release version bump to 0.10.dev0

---

src/ansys/systemcoupling/core/adaptor/impl/syc_proxy.py
src/ansys/systemcoupling/core/util/state_keys.py
tests/test_container.py

Most setting of state in PySystemCoupling - in examples and tutorials and in general practice - is done via the attribute API whereby individual settings are made via path-like chained attributes. For example:
`syc.setup.coupling_interface["intf-1"].target_side = "One"`
It is possible to set state via a dictionary assigned at different levels. For example:
`syc.setup.coupling_interface["intf-1"].set_state({"target_side": "One"})`
or, from a higher level:
`syc.setup.set_state({"coupling_interface":{"intf-1":{"target_side": "One"}}})`
(This is most likely to be useful if multiple settings are made at once via the state dictionary.)
In fact, before the current PR, the second example above did not work. This is because, when this state dictionary is adapted for submission to System Coupling, …

FIX:  handling of named objects in set_state

---

pyproject.toml

Builds on main have failed since this upgrade though the issue isn't obviously with fluent.

MAINT: revert fluent to previous version
